<?php

namespace addons\webman\form;


use addons\webman\form\Driver\Eloquent;
use Illuminate\Database\Eloquent\Model;

class FormManager extends \ExAdmin\ui\manager\FormManager
{
    public function setDriver($repository,$component)
    {
        parent::setDriver($repository,$component); // TODO: Change the autogenerated stub
        if ($repository instanceof Model) {
            $this->driver = new Eloquent();
        }
    }

}
