<?php
/**
 * 总后台功能权限
 */
return [
    // 数据管理
    [
        'id' => 'addons\webman\controller\AdminController\updatePassword',
        'pid' => 0,
        'action' => 'updatePassword',
        'method' => '',
        'group' => 'all',
        'url' => 'ex-admin/addons-webman-controller-AdminController/updatePassword',
        'title' => '修改密码',
    ],
    [
        'id' => 'addons\webman\controller\AdminController\editInfo',
        'pid' => 0,
        'action' => 'editInfo',
        'method' => '',
        'group' => 'all',
        'url' => 'ex-admin/addons-webman-controller-AdminController/editInfo',
        'title' => '个人信息',
    ],
    [
        'id' => 'addons\webman\controller\AdminController\resetPassword',
        'pid' => 0,
        'action' => 'resetPassword',
        'method' => '',
        'group' => 'all',
        'url' => 'ex-admin/addons-webman-controller-AdminController/resetPassword',
        'title' => '重置密码',
    ],
    [
        'id' => 'addons\webman\controller\IndexController\index',
        'pid' => 0,
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-IndexController/index',
        'title' => '数据中心',
    ],
    // 权限管理
    [
        'id' => 'addons\webman\controller\AdminController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '权限管理',
        'children' => []
    ],
    // 用户管理
    [
        'id' => 'addons\webman\controller\AdminController\index',
        'pid' => 'addons\webman\controller\AdminController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AdminController/index',
        'title' => '用户管理',
    ],
    [
        'id' => 'addons\webman\controller\AdminController\index-delete',
        'pid' => 'addons\webman\controller\AdminController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AdminController/index',
        'title' => '删除系统用户',
    ],
    [
        'id' => 'addons\webman\controller\AdminController\form-post',
        'pid' => 'addons\webman\controller\AdminController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AdminController/form',
        'title' => '系统用户添加',
    ],
    [
        'id' => 'addons\webman\controller\AdminController\form-put',
        'pid' => 'addons\webman\controller\AdminController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AdminController/form',
        'title' => '系统用户修改',
    ],
    // 角色管理
    [
        'id' => 'addons\webman\controller\RoleController\index',
        'pid' => 'addons\webman\controller\AdminController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/index',
        'title' => '角色管理',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\index-delete',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/index',
        'title' => '删除系统角色',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\form-post',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/form',
        'title' => '添加系统角色',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\form-put',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/form',
        'title' => '编辑系统角色',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\data',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'data',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/data',
        'title' => '数据权限',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\menu-post',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'menu',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/menu',
        'title' => '添加菜单权限',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\menu-put',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'menu',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/menu',
        'title' => '编辑菜单权限',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\auth-post',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'auth',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/auth',
        'title' => '添加功能权限',
    ],
    [
        'id' => 'addons\webman\controller\RoleController\auth-put',
        'pid' => 'addons\webman\controller\RoleController\index',
        'action' => 'auth',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RoleController/auth',
        'title' => '编辑功能权限',
    ],
    //菜单管理
    [
        'id' => 'addons\webman\controller\MenuController\index',
        'pid' => 'addons\webman\controller\AdminController-',
        'action' => 'index',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MenuController/index',
        'title' => '菜单管理',
    ],
    [
        'id' => 'addons\webman\controller\MenuController\form-post',
        'pid' => 'addons\webman\controller\MenuController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MenuController/form',
        'title' => '添加系统菜单',
    ],
    [
        'id' => 'addons\webman\controller\MenuController\form-put',
        'pid' => 'addons\webman\controller\MenuController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MenuController/form',
        'title' => '编辑系统菜单',
    ],
    //部门管理
    [
        'id' => 'addons\webman\controller\DepartmentController\index',
        'pid' => 'addons\webman\controller\AdminController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepartmentController/index',
        'title' => '部门管理',
    ],
    [
        'id' => 'addons\webman\controller\DepartmentController\index-delete',
        'pid' => 'addons\webman\controller\DepartmentController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepartmentController/index',
        'title' => '删除部门',
    ],
    [
        'id' => 'addons\webman\controller\DepartmentController\form-post',
        'pid' => 'addons\webman\controller\DepartmentController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepartmentController/form',
        'title' => '添加部门',
    ],
    [
        'id' => 'addons\webman\controller\DepartmentController\form-put',
        'pid' => 'addons\webman\controller\DepartmentController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepartmentController/form',
        'title' => '编辑部门',
    ],
    //岗位管理
    [
        'id' => 'addons\webman\controller\PostController\index',
        'pid' => 'addons\webman\controller\AdminController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PostController/index',
        'title' => '岗位管理',
    ],
    [
        'id' => 'addons\webman\controller\PostController\index-delete',
        'pid' => 'addons\webman\controller\PostController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PostController/index',
        'title' => '删除岗位',
    ],
    [
        'id' => 'addons\webman\controller\PostController\form-post',
        'pid' => 'addons\webman\controller\PostController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PostController/form',
        'title' => '添加岗位',
    ],
    [
        'id' => 'addons\webman\controller\PostController\form-put',
        'pid' => 'addons\webman\controller\PostController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PostController/form',
        'title' => '编辑岗位',
    ],
    [
        'id' => 'addons\webman\controller\MachineReportController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '报表中心',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\MachineReportController\index',
        'pid' => 'addons\webman\controller\MachineReportController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineReportController/index',
        'title' => '机台报表',
    ],
    [
        'id' => 'addons\webman\controller\PlayerGameLogController\list',
        'pid' => 'addons\webman\controller\MachineReportController\index',
        'action' => 'list',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerGameLogController/list',
        'title' => '查看明细',
    ],
    [
        'id' => 'addons\webman\controller\PlayerGameLogController\index',
        'pid' => 'addons\webman\controller\MachineReportController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerGameLogController/index',
        'title' => '上下分报表',
    ],
    [
        'id' => 'addons\webman\controller\PlayerReportController\index',
        'pid' => 'addons\webman\controller\MachineReportController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerReportController/index',
        'title' => '玩家报表',
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterReportController\index',
        'pid' => 'addons\webman\controller\MachineReportController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterReportController/index',
        'title' => '全民代理报表',
    ],
    //财务数据
    [
        'id' => 'addons\webman\controller\PresentRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '财务数据',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\WithdrawRecordController\index',
        'pid' => 'addons\webman\controller\PresentRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-WithdrawRecordController/index',
        'title' => '提现记录',
    ],
    [
        'id' => 'addons\webman\controller\RechargeRecordController\index',
        'pid' => 'addons\webman\controller\PresentRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RechargeRecordController/index',
        'title' => '充值记录',
    ],
    [
        'id' => 'addons\webman\controller\PresentRecordController\index',
        'pid' => 'addons\webman\controller\PresentRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PresentRecordController/index',
        'title' => '转点记录',
    ],
    [
        'id' => 'addons\webman\controller\RechargeWithdrawRecordController\index',
        'pid' => 'addons\webman\controller\PresentRecordController-',
        'action' => 'form',
        'method' => 'index',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RechargeWithdrawRecordController/index',
        'title' => '充提记录列表',
    ],

    [
        'id' => 'addons\webman\controller\GameTypeController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '游戏管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\GameTypeController\index',
        'pid' => 'addons\webman\controller\GameTypeController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-GameTypeController/index',
        'title' => '游戏类别',
    ],
    [
        'id' => 'addons\webman\controller\GameTypeController\index-delete',
        'pid' => 'addons\webman\controller\GameTypeController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-GameTypeController/index',
        'title' => '删除游戏类别',
    ],
    [
        'id' => 'addons\webman\controller\GameTypeController\form-post',
        'pid' => 'addons\webman\controller\GameTypeController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-GameTypeController/form',
        'title' => '添加游戏类别',
    ],
    [
        'id' => 'addons\webman\controller\GameTypeController\form-put',
        'pid' => 'addons\webman\controller\GameTypeController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-GameTypeController/form',
        'title' => '编辑游戏类别',
    ],
    [
        'id' => 'addons\webman\controller\MachineCategoryController\index',
        'pid' => 'addons\webman\controller\GameTypeController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineCategoryController/index',
        'title' => '机台类别',
    ],
    [
        'id' => 'addons\webman\controller\MachineCategoryController\index-delete',
        'pid' => 'addons\webman\controller\MachineCategoryController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineCategoryController/index',
        'title' => '删除机台类别',
    ],
    [
        'id' => 'addons\webman\controller\MachineCategoryController\form-post',
        'pid' => 'addons\webman\controller\MachineCategoryController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineCategoryController/form',
        'title' => '添加机台类别',
    ],
    [
        'id' => 'addons\webman\controller\MachineCategoryController\form-put',
        'pid' => 'addons\webman\controller\MachineCategoryController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineCategoryController/form',
        'title' => '编辑机台类别',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\index',
        'pid' => 'addons\webman\controller\GameTypeController-',
        'action' => 'index',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/index',
        'title' => '机台列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\form-post',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/form',
        'title' => '添加机台',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\form-put',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/form',
        'title' => '编辑机台',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\mediaList',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'mediaList',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/mediaList',
        'title' => '媒体列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\changePointCard',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'changePointCard',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/changePointCard',
        'title' => '更换开分卡',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\mediaRecording',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'mediaRecording',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/mediaRecording',
        'title' => '录制列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\getRecording',
        'pid' => 'addons\webman\controller\MachineController\mediaRecording',
        'action' => 'getRecording',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/getRecording',
        'title' => '播放视讯',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\deleteRecording',
        'pid' => 'addons\webman\controller\MachineController\mediaRecording',
        'action' => 'deleteRecording',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/deleteRecording',
        'title' => '删除录像',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\batchDelete',
        'pid' => 'addons\webman\controller\MachineController\mediaRecording',
        'action' => 'batchDelete',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/batchDelete',
        'title' => '批量删除录像',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\clearBet',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'clearBet',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/clearBet',
        'title' => '清理压分',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\rebuildMedia',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'rebuildMedia',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/rebuildMedia',
        'title' => '重设视频流',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\mediaList',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'mediaList',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/mediaList',
        'title' => '视频流列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\mediaDelete',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'mediaDelete',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/mediaDelete',
        'title' => '删除视频流',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\tencentMedia',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'tencentMedia',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/tencentMedia',
        'title' => '腾讯云推流列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\mediaPlay',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'mediaPlay',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/mediaPlay',
        'title' => '播放视频流',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\startRecording',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'startRecording',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/startRecording',
        'title' => '开始录制',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\stopRecording',
        'pid' => 'addons\webman\controller\MachineController\index',
        'action' => 'stopRecording',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/stopRecording',
        'title' => '停止录制录制',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\infoList',
        'pid' => 'addons\webman\controller\GameTypeController-',
        'action' => 'infoList',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/infoList',
        'title' => '机台资讯',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\openCustom',
        'pid' => 'addons\webman\controller\MachineController\infoList',
        'action' => 'openCustom',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/openCustom',
        'title' => '开分自定',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\action',
        'pid' => 'addons\webman\controller\MachineController\infoList',
        'action' => 'action',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/action',
        'title' => '机台操作',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\pushAutoChange',
        'pid' => 'addons\webman\controller\MachineController\infoList',
        'action' => 'pushAutoChange',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/pushAutoChange',
        'title' => 'pushAuto切换',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\changeLock',
        'pid' => 'addons\webman\controller\MachineController\infoList',
        'action' => 'changeLock',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/changeLock',
        'title' => '机台锁切换',
    ],
    [
        'id' => 'addons\webman\controller\MachineController\keepTimeChange',
        'pid' => 'addons\webman\controller\MachineController\infoList',
        'action' => 'keepTimeChange',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineController/keepTimeChange',
        'title' => '调整保留时间',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\changePlayerList',
        'pid' => 'addons\webman\controller\MachineController\infoList',
        'action' => 'changePlayerList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/changePlayerList',
        'title' => '切换玩家',
    ],
    [
        'id' => 'addons\webman\controller\MachineProducerController\index',
        'pid' => 'addons\webman\controller\GameTypeController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineProducerController/index',
        'title' => '厂商列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineProducerController\index-delete',
        'pid' => 'addons\webman\controller\MachineProducerController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineProducerController/index',
        'title' => '删除厂商',
    ],
    [
        'id' => 'addons\webman\controller\MachineProducerController\form-post',
        'pid' => 'addons\webman\controller\MachineProducerController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineProducerController/form',
        'title' => '添加厂商',
    ],
    [
        'id' => 'addons\webman\controller\MachineProducerController\form-put',
        'pid' => 'addons\webman\controller\MachineProducerController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineProducerController/form',
        'title' => '编辑厂商',
    ],
    [
        'id' => 'addons\webman\controller\MachineStrategyController\index',
        'pid' => 'addons\webman\controller\GameTypeController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineStrategyController/index',
        'title' => '机台攻略',
    ],
    [
        'id' => 'addons\webman\controller\MachineStrategyController\index-delete',
        'pid' => 'addons\webman\controller\MachineStrategyController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineStrategyController/index',
        'title' => '删除机台攻略',
    ],
    [
        'id' => 'addons\webman\controller\MachineStrategyController\selectList',
        'pid' => 'addons\webman\controller\MachineStrategyController\index',
        'action' => 'selectList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineStrategyController/selectList',
        'title' => '选择机台攻略列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineStrategyController\form-post',
        'pid' => 'addons\webman\controller\MachineStrategyController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineStrategyController/form',
        'title' => '添加机台攻略',
    ],
    [
        'id' => 'addons\webman\controller\MachineStrategyController\form-put',
        'pid' => 'addons\webman\controller\MachineStrategyController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineStrategyController/form',
        'title' => '编辑机台攻略',
    ],
    [
        'id' => 'addons\webman\controller\MachineLabelController\index',
        'pid' => 'addons\webman\controller\GameTypeController-',
        'action' => 'index',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineLabelController/index',
        'title' => '机台标签列表',
    ],
    [
        'id' => 'addons\webman\controller\MachineLabelController\form',
        'pid' => 'addons\webman\controller\MachineLabelController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineLabelController/form',
        'title' => '编辑机台标签',
    ],
    [
        'id' => 'addons\webman\controller\MachineLabelController\form',
        'pid' => 'addons\webman\controller\MachineLabelController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineLabelController/form',
        'title' => '添加机台标签',
    ],
    //玩家管理
    [
        'id' => 'addons\webman\controller\PlayerController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '玩家管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\PlayerDeliveryRecordController\index',
        'pid' => 'addons\webman\controller\PlayerController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/index',
        'title' => '账变记录',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\index',
        'pid' => 'addons\webman\controller\PlayerController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/index',
        'title' => '设备列表',
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-PlayerController\playerGameWallet',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'playerGameWallet',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/playerGameWallet',
        'title' => '游戏钱包'
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-PlayerController\depositAmount',
        'pid' => 'ex-admin\addons-webman-controller-PlayerController\playerGameWallet',
        'action' => 'depositAmount',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/depositAmount',
        'title' => '转入'
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-PlayerController\withdrawAmount',
        'pid' => 'ex-admin\addons-webman-controller-PlayerController\playerGameWallet',
        'action' => 'withdrawAmount',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/withdrawAmount',
        'title' => '转出'
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-PlayerController\withdrawAmountAll',
        'pid' => 'ex-admin\addons-webman-controller-PlayerController\playerGameWallet',
        'action' => 'withdrawAmountAll',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/withdrawAmountAll',
        'title' => '全部转出'
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\artificialWithdrawal',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'artificialWithdrawal',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/artificialWithdrawal',
        'title' => '人工提现'
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\artificialRecharge',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'artificialRecharge',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/artificialRecharge',
        'title' => '人工充值'
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\index-delete',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/index',
        'title' => '删除玩家',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\form-post',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/form',
        'title' => '添加玩家',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\form-put',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/form',
        'title' => '编辑玩家',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\resetPassword',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'resetPassword',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/resetPassword',
        'title' => '重置密码',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\playerWallet',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'playerWallet',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/playerWallet',
        'title' => '玩家钱包',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\playerBank',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'playerBank',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/playerBank',
        'title' => '银行账户',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\playerBank-delete',
        'pid' => 'addons\webman\controller\PlayerController\playerBank',
        'action' => 'playerBank',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/playerBank',
        'title' => '删除银行账户',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\playerBankForm-post',
        'pid' => 'addons\webman\controller\PlayerController\playerBank',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/playerBankForm',
        'title' => '添加银行账户',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\playerBankForm-put',
        'pid' => 'addons\webman\controller\PlayerController\playerBank',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'addons\webman\controller\PlayerController\playerBankForm',
        'title' => '修改银行账户',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\playerBankChangeStatus',
        'pid' => 'addons\webman\controller\PlayerController\playerBank',
        'action' => 'playerBankChangeStatus',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/playerBankChangeStatus',
        'title' => '修改银行账户状态',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\playerRecord',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'playerRecord',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/playerRecord',
        'title' => '钱包记录',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\bindPromoter',
        'pid' => 'addons\webman\controller\PlayerController\index',
        'action' => 'bindPromoter',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/bindPromoter',
        'title' => '绑定推广员',
    ],
    //彩金管理
    [
        'id' => 'addons\webman\controller\LotteryController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '彩金管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\LotteryController\index',
        'pid' => 'addons\webman\controller\LotteryController-',
        'action' => 'index',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryController/index',
        'title' => '彩金列表',
    ],
    [
        'id' => 'addons\webman\controller\LotteryController\switchStatus',
        'pid' => 'addons\webman\controller\LotteryController\index',
        'action' => 'switchStatus',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryController/switchStatus',
        'title' => '(开启/关闭)彩金池',
    ],
    [
        'id' => 'addons\webman\controller\LotteryController\doubleStatus',
        'pid' => 'addons\webman\controller\LotteryController\index',
        'action' => 'doubleStatus',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryController/doubleStatus',
        'title' => '(开启/关闭)双倍派彩',
    ],
    [
        'id' => 'addons\webman\controller\LotteryController\changeStatus',
        'pid' => 'addons\webman\controller\LotteryController\index',
        'action' => 'changeStatus',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryController/changeStatus',
        'title' => '(开启/关闭)彩金',
    ],
    [
        'id' => 'addons\webman\controller\LotteryController\editLotteryPool',
        'pid' => 'addons\webman\controller\LotteryController\index',
        'action' => 'editLotteryPool',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryController/editLotteryPool',
        'title' => '调整彩金池',
    ],
    [
        'id' => 'addons\webman\controller\LotteryController\form-post',
        'pid' => 'addons\webman\controller\LotteryController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryController/form',
        'title' => '添加彩金',
    ],
    [
        'id' => 'addons\webman\controller\LotteryController\form-put',
        'pid' => 'addons\webman\controller\LotteryController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryController/form',
        'title' => '编辑彩金',
    ],
    [
        'id' => 'addons\webman\controller\PlayerLotteryRecordController\auditList',
        'pid' => 'addons\webman\controller\LotteryController-',
        'action' => 'auditList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerLotteryRecordController/auditList',
        'title' => '彩金审核',
    ],
    [
        'id' => 'addons\webman\controller\PlayerLotteryRecordController\reject',
        'pid' => 'addons\webman\controller\PlayerLotteryRecordController\auditList',
        'action' => 'reject',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerLotteryRecordController/reject',
        'title' => '审核拒绝',
    ],
    [
        'id' => 'addons\webman\controller\PlayerLotteryRecordController\pass',
        'pid' => 'addons\webman\controller\PlayerLotteryRecordController\auditList',
        'action' => 'pass',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerLotteryRecordController/pass',
        'title' => '审核通过',
    ],
    [
        'id' => 'addons\webman\controller\PlayerLotteryRecordController\bathPass',
        'pid' => 'addons\webman\controller\PlayerLotteryRecordController\auditList',
        'action' => 'bathPass',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerLotteryRecordController/bathPass',
        'title' => '批量审核通过',
    ],
    [
        'id' => 'addons\webman\controller\PlayerLotteryRecordController\bathReject',
        'pid' => 'addons\webman\controller\PlayerLotteryRecordController\auditList',
        'action' => 'bathReject',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerLotteryRecordController/bathReject',
        'title' => '批量审核拒绝',
    ],
    [
        'id' => 'addons\webman\controller\PlayerLotteryRecordController\index',
        'pid' => 'addons\webman\controller\LotteryController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerLotteryRecordController/index',
        'title' => '彩金领取列表',
    ],
    [
        'id' => 'addons\webman\controller\PlayerCoinController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '币商管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\coinList',
        'pid' => 'addons\webman\controller\PlayerCoinController-',
        'action' => 'coinList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/coinList',
        'title' => '币商列表',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\coinRecharge',
        'pid' => 'addons\webman\controller\PresentRecordController-',
        'action' => 'coinRecharge',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/coinRecharge',
        'title' => '币商充值',
    ],
    [
        'id' => 'addons\webman\controller\PlayerController\coinWithdraw',
        'pid' => 'addons\webman\controller\PresentRecordController-',
        'action' => 'coinWithdraw',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerController/coinWithdraw',
        'title' => '币商提现',
    ],
    [
        'id' => 'addons\webman\controller\RechargeRecordController\coinList',
        'pid' => 'addons\webman\controller\PlayerCoinController-',
        'action' => 'coinList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-RechargeRecordController/coinList',
        'title' => '币商充值记录',
    ],
    [
        'id' => 'addons\webman\controller\WithdrawRecordController\coinList',
        'pid' => 'addons\webman\controller\PlayerCoinController-',
        'action' => 'coinList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-WithdrawRecordController/coinList',
        'title' => '币商提现记录',
    ],
    [
        'id' => 'addons\webman\controller\GamePlatformController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '电子游戏',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\GamePlatformController\index',
        'pid' => 'addons\webman\controller\GamePlatformController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-GamePlatformController/index',
        'title' => '游戏平台列表',
    ],
    [
        'id' => 'addons\webman\controller\PlayerWalletTransferController\index',
        'pid' => 'addons\webman\controller\GamePlatformController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerWalletTransferController/index',
        'title' => '转账记录',
    ],
    [
        'id' => 'addons\webman\controller\PlayerWalletTransferController\index',
        'pid' => 'addons\webman\controller\GamePlatformController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayGameRecordController/index',
        'title' => '游戏记录',
    ],
    [
        'id' => 'addons\webman\controller\PlayGameRecordController\replay',
        'pid' => 'addons\webman\controller\PlayerWalletTransferController\index',
        'action' => 'replay',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayGameRecordController/replay',
        'title' => '回放',
    ],
    //日志中心
    [
        'id' => 'addons\webman\controller\MachineKeepingLogController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '日志中心',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\MachineKeepingLogController\index',
        'pid' => 'addons\webman\controller\MachineKeepingLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineKeepingLogController/index',
        'title' => '机台保留日志',
    ],
    [
        'id' => 'addons\webman\controller\PlayerEditLogController\index',
        'pid' => 'addons\webman\controller\MachineKeepingLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerEditLogController/index',
        'title' => '玩家资料修改日志',
    ],
    [
        'id' => 'addons\webman\controller\MachineOperationLogController\index',
        'pid' => 'addons\webman\controller\MachineKeepingLogController-',
        'action' => 'index',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineOperationLogController/index',
        'title' => '机台操作日志',
    ],
    [
        'id' => 'addons\webman\controller\MachineEditLogController\index',
        'pid' => 'addons\webman\controller\MachineKeepingLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineEditLogController/index',
        'title' => '机台异动日志',
    ],
    [
        'id' => 'addons\webman\controller\MachineEditLogController\detail',
        'pid' => 'addons\webman\controller\MachineEditLogController\index',
        'action' => 'detail',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineEditLogController/detail',
        'title' => '机台异动日志详情',
    ],
    [
        'id' => 'addons\webman\controller\LotteryAddLogController\index',
        'pid' => 'addons\webman\controller\MachineKeepingLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-LotteryAddLogController/index',
        'title' => '彩金累积日志',
    ],
    [
        'id' => 'addons\webman\controller\PlayerMoneyEditLogController\index',
        'pid' => 'addons\webman\controller\MachineKeepingLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerMoneyEditLogController/index',
        'title' => '玩家钱包操作日志列表',
    ],
    [
        'id' => 'addons\webman\controller\PhoneSmsLogController\index',
        'pid' => 'addons\webman\controller\MachineKeepingLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PhoneSmsLogController/index',
        'title' => '短信日志',
    ],
    //活动管理
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '活动管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\receiveList',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController-',
        'action' => 'receiveList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/receiveList',
        'title' => '活动领取记录'
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\examine',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController\receiveList',
        'action' => 'examine',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/examine',
        'title' => '奖励领取审核',
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\pass',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController\receiveList',
        'action' => 'pass',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/pass',
        'title' => '审核通过'
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\reject',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController\receiveList',
        'action' => 'reject',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/reject',
        'title' => '审核不通过'
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\bathReject',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController\receiveList',
        'action' => 'bathReject',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/bathReject',
        'title' => '批量拒绝'
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\bathPass',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController\receiveList',
        'action' => 'bathPass',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/bathPass',
        'title' => '批量通过'
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\index',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/index',
        'title' => '活动参与记录',
    ],
    [
        'id' => 'addons\webman\controller\PlayerActivityRecordController\playerActivityPhaseRecord',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController\index',
        'action' => 'playerActivityPhaseRecord',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerActivityRecordController/playerActivityPhaseRecord',
        'title' => '玩家领取记录'
    ],
    [
        'id' => 'addons\webman\controller\ActivityController\index',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ActivityController/index',
        'title' => '活动列表',
    ],
    [
        'id' => 'addons\webman\controller\ActivityController\activity-post',
        'pid' => 'addons\webman\controller\ActivityController\index',
        'action' => 'activity',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ActivityController/activity',
        'title' => '添加活动'
    ],
    [
        'id' => 'addons\webman\controller\ActivityController\activity-put',
        'pid' => 'addons\webman\controller\ActivityController\index',
        'action' => 'activity',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ActivityController/activity',
        'title' => '编辑活动'
    ],
    [
        'id' => 'addons\webman\controller\ActivityController\activityOperate',
        'pid' => 'addons\webman\controller\ActivityController\index',
        'action' => 'activityOperate',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ActivityController/activityOperate',
        'title' => '保存活动'
    ],
    [
        'id' => 'addons\webman\controller\ActivityController\editTimeFrame',
        'pid' => 'addons\webman\controller\ActivityController\index',
        'action' => 'editTimeFrame',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ActivityController/editTimeFrame',
        'title' => '编辑活动开放时间'
    ],
    // 充值满赠活动
    [
        'id' => 'addons\webman\controller\DepositBonusActivityController\index',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusActivityController/index',
        'title' => '充值满赠活动',
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusActivityController\form-post',
        'pid' => 'addons\webman\controller\DepositBonusActivityController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusActivityController/form',
        'title' => '添加充值满赠活动'
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusActivityController\form-put',
        'pid' => 'addons\webman\controller\DepositBonusActivityController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusActivityController/form',
        'title' => '编辑充值满赠活动'
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusActivityController\form-get',
        'pid' => 'addons\webman\controller\DepositBonusActivityController\index',
        'action' => 'form',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusActivityController/form',
        'title' => '充值满赠活动表单'
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusActivityController\detail',
        'pid' => 'addons\webman\controller\DepositBonusActivityController\index',
        'action' => 'detail',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusActivityController/detail',
        'title' => '充值满赠活动详情'
    ],
    // 充值满赠订单管理
    [
        'id' => 'addons\webman\controller\DepositBonusQrcodeController\index',
        'pid' => 'addons\webman\controller\PlayerActivityRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusQrcodeController/index',
        'title' => '充值满赠订单',
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusQrcodeController\form-post',
        'pid' => 'addons\webman\controller\DepositBonusQrcodeController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusQrcodeController/form',
        'title' => '生成充值满赠订单'
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusQrcodeController\form-get',
        'pid' => 'addons\webman\controller\DepositBonusQrcodeController\index',
        'action' => 'form',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusQrcodeController/form',
        'title' => '充值满赠订单表单'
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusQrcodeController\detail',
        'pid' => 'addons\webman\controller\DepositBonusQrcodeController\index',
        'action' => 'detail',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusQrcodeController/detail',
        'title' => '充值满赠订单详情'
    ],
    [
        'id' => 'addons\webman\controller\DepositBonusQrcodeController\getActivityOptions',
        'pid' => 'addons\webman\controller\DepositBonusQrcodeController\index',
        'action' => 'getActivityOptions',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-DepositBonusQrcodeController/getActivityOptions',
        'title' => '获取活动选项'
    ],
    //渠道管理
    [
        'id' => 'addons\webman\controller\ChannelController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '渠道管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\CurrencyController\index',
        'pid' => 'addons\webman\controller\ChannelController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-CurrencyController/index',
        'title' => '货币列表',
    ],
    [
        'id' => 'addons\webman\controller\CurrencyController\form-post',
        'pid' => 'addons\webman\controller\CurrencyController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-CurrencyController/form',
        'title' => '添加货币',
    ],
    [
        'id' => 'addons\webman\controller\CurrencyController\form-put',
        'pid' => 'addons\webman\controller\CurrencyController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-CurrencyController/form',
        'title' => '编辑货币',
    ],
    [
        'id' => 'addons\webman\controller\ChannelController\index',
        'pid' => 'addons\webman\controller\ChannelController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelController/index',
        'title' => '渠道列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelController\index-delete',
        'pid' => 'addons\webman\controller\ChannelController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelController/index',
        'title' => '删除渠道',
    ],
    [
        'id' => 'addons\webman\controller\ChannelController\form-post',
        'pid' => 'addons\webman\controller\ChannelController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelController/form',
        'title' => '添加渠道',
    ],
    [
        'id' => 'addons\webman\controller\ChannelController\form-put',
        'pid' => 'addons\webman\controller\ChannelController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelController/form',
        'title' => '编辑渠道',
    ],
    [
        'id' => 'addons\webman\controller\ChannelController\machineList',
        'pid' => 'addons\webman\controller\ChannelController\index',
        'action' => 'machineList',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelController/machineList',
        'title' => '查看渠道机台',
    ],
    [
        'id' => 'addons\webman\controller\ChannelController\addMachine',
        'pid' => 'addons\webman\controller\ChannelController\machineList',
        'action' => 'addMachine',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelController/addMachine',
        'title' => '添加渠道机台',
    ],
    [
        'id' => 'addons\webman\controller\MachineTencentPlayController\index',
        'pid' => 'addons\webman\controller\ChannelController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineTencentPlayController/index',
        'title' => '腾讯云配置',
    ],
    [
        'id' => 'addons\webman\controller\MachineTencentPlayController\form',
        'pid' => 'addons\webman\controller\MachineTencentPlayController\index',
        'action' => 'form',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineTencentPlayController/form',
        'title' => '添加/修改腾讯云配置',
    ],
    [
        'id' => 'addons\webman\controller\MachineTencentPlayController\machineMedia',
        'pid' => 'addons\webman\controller\MachineTencentPlayController\index',
        'action' => 'machineMedia',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-MachineTencentPlayController/machineMedia',
        'title' => '重设推流',
    ],
    [
        'id' => 'addons\webman\controller\ChannelProfitRecordController\index',
        'pid' => 'addons\webman\controller\ChannelController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelProfitRecordController/index',
        'title' => '分润明细',
    ],
    [
        'id' => 'addons\webman\controller\ChannelProfitRecordController\settlementRecord',
        'pid' => 'addons\webman\controller\ChannelController-',
        'action' => 'settlementRecord',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelProfitRecordController/settlementRecord',
        'title' => '渠道分润结算记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelProfitRecordController\settlementDataList',
        'pid' => 'addons\webman\controller\ChannelProfitRecordController\settlementRecord',
        'action' => 'settlementDataList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelProfitRecordController/settlementDataList',
        'title' => '渠道分润结算明细',
    ],
    [
        'id' => 'addons\webman\controller\ChannelProfitRecordController\settlementIndex',
        'pid' => 'addons\webman\controller\ChannelController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelProfitRecordController/settlementIndex',
        'title' => '分润结算',
    ],
    [
        'id' => 'addons\webman\controller\ChannelProfitRecordController\settlement',
        'pid' => 'addons\webman\controller\ChannelProfitRecordController\settlementIndex',
        'action' => 'index',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelProfitRecordController/settlement',
        'title' => '渠道分润结算操作',
    ],
    [
        'id' => 'addons\webman\controller\ChannelProfitRecordController\channelProfitRecordDetail',
        'pid' => 'addons\webman\controller\ChannelProfitRecordController\settlementIndex',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ChannelProfitRecordController/channelProfitRecordDetail',
        'title' => '查看渠道分润明细',
    ],
    //客户端管理
    [
        'id' => 'addons\webman\controller\AnnouncementController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '客户端管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\SystemSettingController\index',
        'pid' => 'addons\webman\controller\AnnouncementController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-SystemSettingController/form',
        'title' => '系统设置',
    ],
    [
        'id' => 'addons\webman\controller\SystemSettingController\editMachineMaintain',
        'pid' => 'addons\webman\controller\SystemSettingController\index',
        'action' => 'editMachineMaintain',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-SystemSettingController/editMachineMaintain',
        'title' => '机台维护时间',
    ],
    [
        'id' => 'addons\webman\controller\SystemSettingController\editKeepingOff',
        'pid' => 'addons\webman\controller\SystemSettingController\index',
        'action' => 'editKeepingOff',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-SystemSettingController/editKeepingOff',
        'title' => '机台保留停止时段',
    ],
    [
        'id' => 'addons\webman\controller\AnnouncementController\index',
        'pid' => 'addons\webman\controller\AnnouncementController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AnnouncementController/index',
        'title' => '公告列表',
    ],
    [
        'id' => 'addons\webman\controller\AnnouncementController\index-delete',
        'pid' => 'addons\webman\controller\AnnouncementController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AnnouncementController/index',
        'title' => '删除公告',
    ],
    [
        'id' => 'addons\webman\controller\AnnouncementController\form-post',
        'pid' => 'addons\webman\controller\AnnouncementController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AnnouncementController/form',
        'title' => '添加公告',
    ],
    [
        'id' => 'addons\webman\controller\AnnouncementController\form-put',
        'pid' => 'addons\webman\controller\AnnouncementController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AnnouncementController/form',
        'title' => '编辑公告',
    ],
    [
        'id' => 'addons\webman\controller\SliderController\index',
        'pid' => 'addons\webman\controller\AnnouncementController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-SliderController/index',
        'title' => '轮播图列表',
    ],
    [
        'id' => 'addons\webman\controller\SliderController\index-delete',
        'pid' => 'addons\webman\controller\SliderController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-SliderController/index',
        'title' => '删除轮播图',
    ],
    [
        'id' => 'addons\webman\controller\SliderController\form-post',
        'pid' => 'addons\webman\controller\SliderController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-SliderController/form',
        'title' => '添加轮播图',
    ],
    [
        'id' => 'addons\webman\controller\SliderController\form-put',
        'pid' => 'addons\webman\controller\SliderController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-SliderController/form',
        'title' => '编辑轮播图',
    ],
    //系统管理
    [
        'id' => 'addons\webman\controller\ConfigController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '系统管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ConfigController\form-get',
        'pid' => 'addons\webman\controller\ConfigController-',
        'action' => 'form',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ConfigController/form',
        'title' => '查看系统配置',
    ],
    [
        'id' => 'addons\webman\controller\ConfigController\form-post',
        'pid' => 'addons\webman\controller\ConfigController-',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-ConfigController/form',
        'title' => '编辑系统配置',
    ],
    [
        'id' => 'addons\webman\controller\AttachmentController\index',
        'pid' => 'addons\webman\controller\ConfigController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AttachmentController/index',
        'title' => '附件列表',
    ],
    [
        'id' => 'addons\webman\controller\AttachmentController\index-delete',
        'pid' => 'addons\webman\controller\AttachmentController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AttachmentController/index',
        'title' => '删除附件',
    ],
    [
        'id' => 'addons\webman\controller\AttachmentController\cate',
        'pid' => 'addons\webman\controller\AttachmentController\index',
        'action' => 'cate',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AttachmentController/index',
        'title' => '附件分类',
    ],
    //全民代理管理
    [
        'id' => 'addons\webman\controller\NationalPromoterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '全民代理管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterController\index',
        'pid' => 'addons\webman\controller\NationalPromoterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterController/index',
        'title' => '全民代理设置',
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterController\levelDetail',
        'pid' => 'addons\webman\controller\NationalPromoterController-',
        'action' => 'levelDetail',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterController/levelDetail',
        'title' => '全民代理详情',
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterController\form',
        'pid' => 'addons\webman\controller\NationalPromoterController\levelDetail',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterController/form',
        'title' => '全民代理编辑',
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterController\nationalInvite',
        'pid' => 'addons\webman\controller\NationalPromoterController-',
        'action' => 'nationalInvite',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterController/nationalInvite',
        'title' => '邀请人数奖励',
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterController\form',
        'pid' => 'addons\webman\controller\NationalPromoterController\nationalInvite',
        'action' => 'addInviteConfig',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterController/addInviteConfig',
        'title' => '添加邀请人数奖励',
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterController\addInviteConfig',
        'pid' => 'addons\webman\controller\NationalPromoterController\nationalInvite',
        'action' => 'addInviteConfig',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterController/addInviteConfig',
        'title' => '编辑邀请人数奖励',
    ],
    [
        'id' => 'addons\webman\controller\NationalPromoterController\record',
        'pid' => 'addons\webman\controller\NationalPromoterController-',
        'action' => 'record',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-NationalPromoterController/record',
        'title' => '返佣记录',
    ],
    //银行列表
    [
        'id' => 'addons\webman\controller\BankController\index',
        'pid' => 'addons\webman\controller\PresentRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-BankController/index',
        'title' => '银行列表',
    ],
    [
        'id' => 'addons\webman\controller\BankController\form-post',
        'pid' => 'addons\webman\controller\BankController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-BankController/form',
        'title' => '添加银行',
    ],
    [
        'id' => 'addons\webman\controller\BankController\form-put',
        'pid' => 'addons\webman\controller\BankController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-BankController/form',
        'title' => '编辑银行',
    ],

    //反水管理
    [
        'id' => 'addons\webman\controller\PlatformReverseWaterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '反水管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\PlatformReverseWaterController\index',
        'pid' => 'addons\webman\controller\PlatformReverseWaterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformReverseWaterController/index',
        'title' => '反水活动',
    ],
    [
        'id' => 'addons\webman\controller\PlatformReverseWaterController\waterDetail',
        'pid' => 'addons\webman\controller\PlatformReverseWaterController-',
        'action' => 'waterDetail',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformReverseWaterController/waterDetail',
        'title' => '反水奖励记录',
    ],
    [
        'id' => 'addons\webman\controller\PlatformReverseWaterController\form-post',
        'pid' => 'addons\webman\controller\PlatformReverseWaterController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformReverseWaterController/form',
        'title' => '添加配置',
    ],
    [
        'id' => 'addons\webman\controller\PlatformReverseWaterController\form-put',
        'pid' => 'addons\webman\controller\PlatformReverseWaterController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformReverseWaterController/form',
        'title' => '修改配置',
    ],
    //推广员管理
    [
        'id' => 'addons\webman\controller\PlayerPromoterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '推广管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\PlayerPromoterController\index',
        'pid' => 'addons\webman\controller\PlayerPromoterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerPromoterController/index',
        'title' => '推广员列表',
    ],
    [
        'id' => 'addons\webman\controller\PlayerPromoterController\reportList',
        'pid' => 'addons\webman\controller\PlayerPromoterController-',
        'action' => 'reportList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerPromoterController/reportList',
        'title' => '分润报表',
    ],
    [
        'id' => 'addons\webman\controller\PlayerPromoterController\settlementList',
        'pid' => 'addons\webman\controller\PlayerPromoterController-',
        'action' => 'settlementList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerPromoterController/settlementList',
        'title' => '分润结算记录',
    ],
    [
        'id' => 'addons\webman\controller\PlayerPromoterController\settlementDataList',
        'pid' => 'addons\webman\controller\PlayerPromoterController\settlementList',
        'action' => 'settlementDataList',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlayerPromoterController/settlementDataList',
        'title' => '结算详情',
    ],
    //线下代理管理
    [
        'id' => 'addons\webman\controller\ChannelAgentPromoterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '线下代理管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\AgentPromoterController\index',
        'pid' => 'addons\webman\controller\AgentPromoterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AgentPromoterController/index',
        'title' => '代理列表',
    ],
    [
        'id' => 'addons\webman\controller\AgentPromoterController\settlement',
        'pid' => 'addons\webman\controller\AgentPromoterController\index',
        'action' => 'settlement',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AgentPromoterController/settlement',
        'title' => '分润结算',
    ],
    [
        'id' => 'addons\webman\controller\AgentPromoterController\bathSettlement',
        'pid' => 'addons\webman\controller\AgentPromoterController\index',
        'action' => 'bathSettlement',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AgentPromoterController/bathSettlement',
        'title' => '批量结算',
    ],
    [
        'id' => 'addons\webman\controller\AgentPromoterController\settlementList',
        'pid' => 'addons\webman\controller\AgentPromoterController-',
        'action' => 'settlementList',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-AgentPlayerPromoterController/settlementList',
        'title' => '分润结算记录',
    ],
    // 限红管理
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupController-',
        'pid' => 0,
        'url' => '',
        'group' => 'department',
        'title' => '限红管理',
        'children' => []
    ],
    // 限红组管理
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupController\index',
        'pid' => 'addons\webman\controller\PlatformLimitGroupController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupController/index',
        'title' => '限红组管理',
    ],
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupController\index-delete',
        'pid' => 'addons\webman\controller\PlatformLimitGroupController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupController/index',
        'title' => '删除限红组',
    ],
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupController\form-post',
        'pid' => 'addons\webman\controller\PlatformLimitGroupController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupController/form',
        'title' => '添加限红组',
    ],
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupController\form-put',
        'pid' => 'addons\webman\controller\PlatformLimitGroupController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupController/form',
        'title' => '修改限红组',
    ],
    // 限红组平台配置
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupConfigController\index',
        'pid' => 'addons\webman\controller\PlatformLimitGroupController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupConfigController/index',
        'title' => '限红组平台配置',
    ],
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupConfigController\index-delete',
        'pid' => 'addons\webman\controller\PlatformLimitGroupConfigController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupConfigController/index',
        'title' => '删除平台配置',
    ],
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupConfigController\form-post',
        'pid' => 'addons\webman\controller\PlatformLimitGroupConfigController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupConfigController/form',
        'title' => '添加平台配置',
    ],
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupConfigController\form-put',
        'pid' => 'addons\webman\controller\PlatformLimitGroupConfigController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupConfigController/form',
        'title' => '修改平台配置',
    ],
    [
        'id' => 'addons\webman\controller\PlatformLimitGroupConfigController\getLimitGroupOptions',
        'pid' => 'addons\webman\controller\PlatformLimitGroupConfigController\index',
        'action' => 'getLimitGroupOptions',
        'method' => '',
        'group' => 'department',
        'url' => 'ex-admin/addons-webman-controller-PlatformLimitGroupConfigController/getLimitGroupOptions',
        'title' => '获取限红组选项',
    ],
];
