<?php
/**
 * 渠道后台功能权限
 */
return [
    [
        'id' => 'addons\webman\controller\ChannelIndexController\index',
        'pid' => 0,
        'action' => 'index',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelIndexController/index',
        'title' => '数据中心',
    ],

    //用户管理
    [
        'id' => 'addons\webman\controller\ChannelAdminController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '权限管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminController\index',
        'pid' => 'addons\webman\controller\ChannelAdminController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminController/index',
        'title' => '系统用户列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminController\index-delete',
        'pid' => 'addons\webman\controller\ChannelAdminController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminController/index',
        'title' => '删除系统用户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminController\resetPassword',
        'pid' => 'addons\webman\controller\ChannelAdminController\index',
        'action' => 'resetPassword',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminController/resetPassword',
        'title' => '重置密码',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminController\bindAgent',
        'pid' => 'addons\webman\controller\ChannelAdminController\index',
        'action' => 'bindAgent',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminController/bindAgent',
        'title' => '绑定代理',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminController\form-post',
        'pid' => 'addons\webman\controller\ChannelAdminController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminController/form',
        'title' => '添加系统用户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminController\form-put',
        'pid' => 'addons\webman\controller\ChannelAdminController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminController/form',
        'title' => '编辑系统用户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPostController\index',
        'pid' => 'addons\webman\controller\ChannelAdminController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPostController/index',
        'title' => '岗位列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPostController\index-delete',
        'pid' => 'addons\webman\controller\ChannelPostController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPostController/index',
        'title' => '删除岗位',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPostController\form-post',
        'pid' => 'addons\webman\controller\ChannelPostController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPostController/form',
        'title' => '添加岗位',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPostController\form-put',
        'pid' => 'addons\webman\controller\ChannelPostController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPostController/form',
        'title' => '编辑岗位',
    ],
    //渠道推广员管理
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '推广管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/index',
        'title' => '推广员列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPromoterProfitGameRecordController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPromoterProfitGameRecordController/index',
        'title' => '游戏平台分润',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPromoterProfitGameRecordController\playGameRecordList',
        'pid' => 'addons\webman\controller\ChannelPromoterProfitGameRecordController\index',
        'action' => 'playGameRecordList',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPromoterProfitGameRecordController/playGameRecordList',
        'title' => '游戏记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\setSettlementDate',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController\index',
        'action' => 'setSettlementDate',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/setSettlementDate',
        'title' => '设置结算日',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\settlement',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController\index',
        'action' => 'settlement',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/settlement',
        'title' => '分润结算',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\profitSettlement',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController\index',
        'action' => 'profitSettlement',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/profitSettlement',
        'title' => '批量结算',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\settlement',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController\index',
        'action' => 'settlement',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/settlement',
        'title' => '分润结算',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\reportList',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController-',
        'action' => 'reportList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/reportList',
        'title' => '分润报表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\settlementList',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController-',
        'action' => 'settlementList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/settlementList',
        'title' => '分润结算记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerPromoterController\settlementDataList',
        'pid' => 'addons\webman\controller\ChannelPlayerPromoterController\settlementList',
        'action' => 'settlementDataList',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerPromoterController/settlementDataList',
        'title' => '结算详情',
    ],
    //线下代理管理
    [
        'id' => 'addons\webman\controller\ChannelAgentPromoterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '线下代理管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelAgentPromoterController\index',
        'pid' => 'addons\webman\controller\ChannelAgentPromoterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAgentPromoterController/index',
        'title' => '代理列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAgentPromoterController\settlement',
        'pid' => 'addons\webman\controller\ChannelAgentPromoterController\index',
        'action' => 'settlement',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAgentPromoterController/settlement',
        'title' => '分润结算',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAgentPromoterController\bathSettlement',
        'pid' => 'addons\webman\controller\ChannelAgentPromoterController\index',
        'action' => 'bathSettlement',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAgentPromoterController/bathSettlement',
        'title' => '批量结算',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAgentPromoterController\settlementList',
        'pid' => 'addons\webman\controller\ChannelAgentPromoterController-',
        'action' => 'settlementList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAgentPlayerPromoterController/settlementList',
        'title' => '分润结算记录',
    ],
    // 渠道玩家质料修改日志
    [
        'id' => 'addons\webman\controller\ChannelPlayerEditLogController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '日志中心',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelMachineOperationLogController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerEditLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMachineOperationLogController/index',
        'title' => '机台操作日志',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerEditLogController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerEditLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerEditLogController/index',
        'title' => '玩家质料修改日志',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerMoneyEditLogController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerEditLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerMoneyEditLogController/index',
        'title' => '玩家钱包操作日志',
    ],
    [
        'id' => 'addons\webman\controller\ChannelMachineKeepingLogController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerEditLogController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMachineKeepingLogController/index',
        'title' => '机台保留日志',
    ],
    //活动管理
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '活动管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\receiveList',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController-',
        'action' => 'receiveList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/receiveList',
        'title' => '活动领取记录'
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\examine',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController\receiveList',
        'action' => 'examine',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/examine',
        'title' => '奖励领取审核',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\pass',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController\receiveList',
        'action' => 'pass',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/pass',
        'title' => '审核通过'
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\reject',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController\receiveList',
        'action' => 'reject',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/reject',
        'title' => '审核不通过'
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\bathReject',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController\receiveList',
        'action' => 'bathReject',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/bathReject',
        'title' => '批量拒绝'
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\bathPass',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController\receiveList',
        'action' => 'bathPass',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/bathPass',
        'title' => '批量通过'
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/index',
        'title' => '活动参与记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerActivityRecordController\playerActivityPhaseRecord',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController\index',
        'action' => 'playerActivityPhaseRecord',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerActivityRecordController/playerActivityPhaseRecord',
        'title' => '玩家领取记录'
    ],
    [
        'id' => 'addons\webman\controller\ChannelActivityController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerActivityRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelActivityController/index',
        'title' => '活动列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayGameRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '电子游戏',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayGameRecordController\index',
        'pid' => 'addons\webman\controller\ChannelPlayGameRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayGameRecordController/index',
        'title' => '游戏记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayGameRecordController\replay',
        'pid' => 'addons\webman\controller\ChannelPlayGameRecordController\index',
        'action' => 'replay',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayGameRecordController/replay',
        'title' => '回放',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerWalletTransferController\index',
        'pid' => 'addons\webman\controller\ChannelPlayGameRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerWalletTransferController/index',
        'title' => '转账记录',
    ],
    //分润管理
    [
        'id' => 'addons\webman\controller\ChannelChannelProfitRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '分润管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelChannelProfitRecordController\index',
        'pid' => 'addons\webman\controller\ChannelChannelProfitRecordController-',
        'action' => 'auditList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelChannelProfitRecordController/index',
        'title' => '分润明细',
    ],
    [
        'id' => 'addons\webman\controller\ChannelChannelProfitRecordController\settlementIndex',
        'pid' => 'addons\webman\controller\ChannelChannelProfitRecordController-',
        'action' => 'auditList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelChannelProfitRecordController/settlementIndex',
        'title' => '分润结算记录',
    ],
    //彩金管理
    [
        'id' => 'addons\webman\controller\ChannelPlayerLotteryRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '彩金管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\auditList',
        'pid' => 'addons\webman\controller\ChannelPlayerLotteryRecordController-',
        'action' => 'auditList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerLotteryRecordController/auditList',
        'title' => '彩金审核',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\reject',
        'pid' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\auditList',
        'action' => 'reject',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerLotteryRecordController/reject',
        'title' => '审核拒绝',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\pass',
        'pid' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\auditList',
        'action' => 'pass',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerLotteryRecordController/pass',
        'title' => '审核通过',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\bathPass',
        'pid' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\auditList',
        'action' => 'bathPass',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerLotteryRecordController/bathPass',
        'title' => '批量审核通过',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\bathReject',
        'pid' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\auditList',
        'action' => 'bathReject',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerLotteryRecordController/bathReject',
        'title' => '批量审核拒绝',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerLotteryRecordController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerLotteryRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerLotteryRecordController/index',
        'title' => '彩金领取记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPresentRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '币商管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\coinList',
        'pid' => 'addons\webman\controller\ChannelPresentRecordController-',
        'action' => 'coinList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/coinList',
        'title' => '币商列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\setCoin',
        'pid' => 'addons\webman\controller\ChannelPresentRecordController-',
        'action' => 'setCoin',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/setCoin',
        'title' => '(设置/取消)币商',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\coinRecharge',
        'pid' => 'addons\webman\controller\ChannelPresentRecordController-',
        'action' => 'coinRecharge',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/coinRecharge',
        'title' => '币商充值',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\coinWithdraw',
        'pid' => 'addons\webman\controller\ChannelPresentRecordController-',
        'action' => 'coinWithdraw',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/coinWithdraw',
        'title' => '币商提现',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\coinList',
        'pid' => 'addons\webman\controller\ChannelPresentRecordController-',
        'action' => 'coinList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/coinList',
        'title' => '币商充值记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\coinList',
        'pid' => 'addons\webman\controller\ChannelPresentRecordController-',
        'action' => 'coinList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/coinList',
        'title' => '币商提现记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPresentRecordController\coinList',
        'pid' => 'addons\webman\controller\ChannelPresentRecordController-',
        'action' => 'coinList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPresentRecordController/coinList',
        'title' => '币商交易记录',
    ],
    // 代理管理（线下渠道）
    [
        'id' => 'addons\webman\controller\AgentController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '代理管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\AgentController\index',
        'pid' => 'addons\webman\controller\AgentController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-AgentController/index',
        'title' => '代理列表',
    ],
    [
        'id' => 'addons\webman\controller\AgentController\createAgentForm',
        'pid' => 'addons\webman\controller\AgentController\index',
        'action' => 'createAgentForm',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-AgentController/createAgentForm',
        'title' => '创建代理',
    ],
    [
        'id' => 'addons\webman\controller\AgentController\createAgentForm-post',
        'pid' => 'addons\webman\controller\AgentController\createAgentForm',
        'action' => 'createAgentForm',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-AgentController/createAgentForm',
        'title' => '创建代理保存',
    ],
    [
        'id' => 'addons\webman\controller\AgentController\getAgentOptions',
        'pid' => 'addons\webman\controller\AgentController\index',
        'action' => 'getAgentOptions',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-AgentController/getAgentOptions',
        'title' => '获取代理选项',
    ],

    // 店家管理（线下渠道）
    [
        'id' => 'addons\webman\controller\StoreMachineController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '店家管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\StoreMachineController\index',
        'pid' => 'addons\webman\controller\StoreMachineController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-StoreMachineController/index',
        'title' => '店家列表',
    ],
    [
        'id' => 'addons\webman\controller\StoreMachineController\createStoreMachineForm',
        'pid' => 'addons\webman\controller\StoreMachineController\index',
        'action' => 'createStoreMachineForm',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-StoreMachineController/createStoreMachineForm',
        'title' => '创建店家',
    ],
    [
        'id' => 'addons\webman\controller\StoreMachineController\createStoreMachineForm-post',
        'pid' => 'addons\webman\controller\StoreMachineController\createStoreMachineForm',
        'action' => 'createStoreMachineForm',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-StoreMachineController/createStoreMachineForm',
        'title' => '创建店家保存',
    ],
    [
        'id' => 'addons\webman\controller\StoreMachineController\getAgentOptions',
        'pid' => 'addons\webman\controller\StoreMachineController\index',
        'action' => 'getAgentOptions',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-StoreMachineController/getAgentOptions',
        'title' => '获取代理选项',
    ],
    [
        'id' => 'addons\webman\controller\StoreMachineController\platformAccountList',
        'pid' => 'addons\webman\controller\StoreMachineController\index',
        'action' => 'platformAccountList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-StoreMachineController/platformAccountList',
        'title' => '第三方游戏平台账号',
    ],

    //玩家管理
    [
        'id' => 'addons\webman\controller\ChannelPlayerController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '玩家管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/index',
        'title' => '设备列表',
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-ChannelPlayerController\playerGameWallet',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'playerGameWallet',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/playerGameWallet',
        'title' => '游戏钱包'
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-ChannelPlayerController\depositAmount',
        'pid' => 'ex-admin\addons-webman-controller-ChannelPlayerController\playerGameWallet',
        'action' => 'depositAmount',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/depositAmount',
        'title' => '转入'
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-ChannelPlayerController\withdrawAmount',
        'pid' => 'ex-admin\addons-webman-controller-ChannelPlayerController\playerGameWallet',
        'action' => 'withdrawAmount',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/withdrawAmount',
        'title' => '转出'
    ],
    [
        'id' => 'ex-admin\addons-webman-controller-ChannelPlayerController\withdrawAmountAll',
        'pid' => 'ex-admin\addons-webman-controller-ChannelPlayerController\playerGameWallet',
        'action' => 'withdrawAmountAll',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/withdrawAmountAll',
        'title' => '全部转出'
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\form-post',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/form',
        'title' => '添加玩家',
    ],
    [
        'id' => 'addons\webman\service\ImportService\importPlayer',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'importPlayer',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-service-ImportService/importPlayer',
        'title' => '导入',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\form-put',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/form',
        'title' => '编辑玩家',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\index-delete',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/index',
        'title' => '删除玩家',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\createAgentForm',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'createAgentForm',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/createAgentForm',
        'title' => '创建代理',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\createAgentSaving',
        'pid' => 'addons\webman\controller\ChannelPlayerController\createAgentForm',
        'action' => 'createAgentSaving',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/createAgentForm',
        'title' => '创建代理保存',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\createStoreMachineForm',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'createStoreMachineForm',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/createStoreMachineForm',
        'title' => '创建店家',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\createStoreMachineSaving',
        'pid' => 'addons\webman\controller\ChannelPlayerController\createStoreMachineForm',
        'action' => 'createStoreMachineSaving',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/createStoreMachineForm',
        'title' => '创建店家保存',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\batchGenerateForm',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'batchGenerateForm',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/batchGenerateForm',
        'title' => '批量生成玩家',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\batchGeneratePlayersSaving',
        'pid' => 'addons\webman\controller\ChannelPlayerController\batchGenerateForm',
        'action' => 'batchGeneratePlayersSaving',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/batchGenerateForm',
        'title' => '批量生成玩家保存',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\playerRecord',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'playerRecord',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/playerRecord',
        'title' => '钱包余额-查看记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\playerWallet',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'playerWallet',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/playerWallet',
        'title' => '玩家钱包',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\artificialWithdrawal',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'artificialWithdrawal',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/artificialWithdrawal',
        'title' => '人工提现',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\artificialRecharge',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'artificialRecharge',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/artificialRecharge',
        'title' => '开分',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\toggleGamePlatform',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'toggleGamePlatform',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/toggleGamePlatform',
        'title' => '电子游戏禁用/启用',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\setPromoter',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'setPromoter',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/setPromoter',
        'title' => '设置推广员',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\playerBank',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'playerBank',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/playerBank',
        'title' => '银行账户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\playerBank-delete',
        'pid' => 'addons\webman\controller\ChannelPlayerController\playerBank',
        'action' => 'playerBank',
        'method' => 'delete',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/playerBank',
        'title' => '删除银行账户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\playerBankForm-post',
        'pid' => 'addons\webman\controller\ChannelPlayerController\playerBank',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/playerBankForm',
        'title' => '添加银行账户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\playerBankForm-put',
        'pid' => 'addons\webman\controller\ChannelPlayerController\playerBank',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'addons\webman\controller\ChannelPlayerController\playerBankForm',
        'title' => '修改银行账户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\playerBankChangeStatus',
        'pid' => 'addons\webman\controller\ChannelPlayerController\playerBank',
        'action' => 'playerBankChangeStatus',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/playerBankChangeStatus',
        'title' => '修改银行账户状态',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerDeliveryRecordController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerDeliveryRecordController/index',
        'title' => '账变记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerReportController\index',
        'pid' => 'addons\webman\controller\ChannelPlayerController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerReportController/index',
        'title' => '玩家报表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\bindPromoter',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'bindPromoter',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/bindPromoter',
        'title' => '绑定推广员',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerController\toggleGameDisable',
        'pid' => 'addons\webman\controller\ChannelPlayerController\index',
        'action' => 'toggleGameDisable',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerController/toggleGameDisable',
        'title' => '切换游戏禁用状态',
    ],
    //机台管理
    [
        'id' => 'addons\webman\controller\ChannelMachineController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '机台管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelMachineController\index',
        'pid' => 'addons\webman\controller\ChannelMachineController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMachineController/index',
        'title' => '机器列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerGameLogController\index',
        'pid' => 'addons\webman\controller\ChannelMachineController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerGameLogController/index',
        'title' => '上下分记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelMachineReportController\index',
        'pid' => 'addons\webman\controller\ChannelMachineController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMachineReportController/index',
        'title' => '机台报表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlayerGameLogController\list',
        'pid' => 'addons\webman\controller\ChannelMachineReportController\index',
        'action' => 'list',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlayerGameLogController/list',
        'title' => '机台报表明细',
    ],
    [
        'id' => 'addons\webman\controller\ChannelStoreProfitReportController\index',
        'pid' => 'addons\webman\controller\ChannelMachineController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelStoreProfitReportController/index',
        'title' => '店家分润报表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelMachineController\infoList',
        'pid' => 'addons\webman\controller\ChannelMachineController-',
        'action' => 'infoList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMachineController/infoList',
        'title' => '机台资讯',
    ],
    [
        'id' => 'addons\webman\controller\ChannelMachineController\action',
        'pid' => 'addons\webman\controller\ChannelMachineController\infoList',
        'action' => 'action',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMachineController/action',
        'title' => '机台资讯操作',
    ],
    [
        'id' => 'addons\webman\controller\ChannelMachineController\mediaPlay',
        'pid' => 'addons\webman\controller\ChannelMachineController\infoList',
        'action' => 'mediaPlay',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMachineController/mediaPlay',
        'title' => '播放视讯',
    ],
    //轮播图管理
    [
        'id' => 'addons\webman\controller\ChannelSliderController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '客户端管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelSliderController\index',
        'pid' => 'addons\webman\controller\ChannelSliderController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelSliderController/index',
        'title' => '轮播图列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelSliderController\index-delete',
        'pid' => 'addons\webman\controller\ChannelSliderController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelSliderController/index',
        'title' => '删除轮播图',
    ],
    [
        'id' => 'addons\webman\controller\ChannelSliderController\form-post',
        'pid' => 'addons\webman\controller\ChannelSliderController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelSliderController/form',
        'title' => '添加轮播图',
    ],
    [
        'id' => 'addons\webman\controller\ChannelSliderController\form-put',
        'pid' => 'addons\webman\controller\ChannelSliderController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelSliderController/form',
        'title' => '编辑轮播图',
    ],
    [
        'id' => 'addons\webman\controller\ChannelMarqueeController\index',
        'pid' => 'addons\webman\controller\ChannelSliderController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelMarqueeController/index',
        'title' => '跑马灯列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAnnouncementController\index',
        'pid' => 'addons\webman\controller\ChannelSliderController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAnnouncementController/index',
        'title' => '公告列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAnnouncementController\index-delete',
        'pid' => 'addons\webman\controller\ChannelAnnouncementController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAnnouncementController/index',
        'title' => '删除公告',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAnnouncementController\form-post',
        'pid' => 'addons\webman\controller\ChannelAnnouncementController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAnnouncementController/form',
        'title' => '添加公告',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAnnouncementController\form-put',
        'pid' => 'addons\webman\controller\ChannelAnnouncementController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAnnouncementController/form',
        'title' => '编辑公告',
    ],
    //财务管理
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '财务管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\talkIndex',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'talkIndex',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/talkIndex',
        'title' => 'Q-talk充值记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\index',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/index',
        'title' => '提现记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\talkIndex',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'talkIndex',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/talkIndex',
        'title' => 'Q-talk提現记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeController\index',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeController/index',
        'title' => '充值渠道配置',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeController\methodForm-post',
        'pid' => 'addons\webman\controller\ChannelRechargeController\index',
        'action' => 'methodForm',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeController/methodForm',
        'title' => '添加充值方式',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeController\methodForm',
        'pid' => 'addons\webman\controller\ChannelRechargeController\index',
        'action' => 'methodForm',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeController/methodForm',
        'title' => '编辑充值方式',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeController\form',
        'pid' => 'addons\webman\controller\ChannelRechargeController\index',
        'action' => 'form',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeController/form',
        'title' => '添加充值账户',
    ],
    [
        'id' => 'addons\webman\controller\ChannelFinancialRecordController\index',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelFinancialRecordController/index',
        'title' => '财务操作记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\index',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/index',
        'title' => '充值记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeWithdrawRecordController\index',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'index',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeWithdrawRecordController/index',
        'title' => '充提记录列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\examineList',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'examineList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/examineList',
        'title' => '充值审核',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\reject',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController\examineList',
        'action' => 'reject',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/reject',
        'title' => '审核拒绝',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\pass',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController\examineList',
        'action' => 'pass',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/pass',
        'title' => '审核通过',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\rechargeCertificate',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController\examineList',
        'action' => 'rechargeCertificate',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/rechargeCertificate',
        'title' => '查看付款凭证',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\uploadCertificate',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController\examineList',
        'action' => 'uploadCertificate',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/uploadCertificate',
        'title' => '上传付款凭证',
    ],
    [
        'id' => 'addons\webman\controller\ChannelRechargeRecordController\rechargeSetting',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController\examineList',
        'action' => 'rechargeSetting',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelRechargeRecordController/rechargeSetting',
        'title' => '查看充值账号配置',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\examineList',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'examineList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/examineList',
        'title' => '提现审核',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\viewRechargeList',
        'pid' => 'addons\webman\controller\ChannelWithdrawRecordController\examineList',
        'action' => 'viewRechargeList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/viewRechargeList',
        'title' => '查看充值记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\viewGameList',
        'pid' => 'addons\webman\controller\ChannelWithdrawRecordController\examineList',
        'action' => 'viewGameList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/viewGameList',
        'title' => '查看游戏记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\reject',
        'pid' => 'addons\webman\controller\ChannelWithdrawRecordController\examineList',
        'action' => 'reject',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/reject',
        'title' => '审核拒绝',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\pass',
        'pid' => 'addons\webman\controller\ChannelWithdrawRecordController\examineList',
        'action' => 'pass',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/pass',
        'title' => '审核通过',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\paymentList',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'paymentList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/paymentList',
        'title' => '提现打款',
    ],
    [
        'id' => 'addons\webman\controller\ChannelWithdrawRecordController\payment',
        'pid' => 'addons\webman\controller\ChannelWithdrawRecordController\paymentList',
        'action' => 'payment',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelWithdrawRecordController/payment',
        'title' => '提交打款凭证',
    ],
    //全民代理管理
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '全民代理管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\index',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/index',
        'title' => '全民代理设置',
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\levelDetail',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController-',
        'action' => 'levelDetail',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/levelDetail',
        'title' => '全民代理详情',
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\form',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController\levelDetail',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/form',
        'title' => '全民代理编辑',
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\nationalInvite',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController-',
        'action' => 'nationalInvite',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/nationalInvite',
        'title' => '邀请人数奖励',
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\addInviteConfig',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController\nationalInvite',
        'action' => 'addInviteConfig',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/addInviteConfig',
        'title' => '添加邀请人数奖励',
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\addInviteConfig',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController\nationalInvite',
        'action' => 'addInviteConfig',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/addInviteConfig',
        'title' => '编辑邀请人数奖励',
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\record',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController-',
        'action' => 'record',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/record',
        'title' => '返佣记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelNationalPromoterController\reportList',
        'pid' => 'addons\webman\controller\ChannelNationalPromoterController-',
        'action' => 'reportList',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelNationalPromoterController/reportList',
        'title' => '分润明细',
    ],
    //银行列表
    [
        'id' => 'addons\webman\controller\ChannelBankController\index',
        'pid' => 'addons\webman\controller\ChannelRechargeRecordController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelBankController/index',
        'title' => '银行列表',
    ],
    [
        'id' => 'addons\webman\controller\ChannelBankController\form-post',
        'pid' => 'addons\webman\controller\ChannelBankController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelBankController/form',
        'title' => '添加银行',
    ],
    [
        'id' => 'addons\webman\controller\ChannelBankController\form-put',
        'pid' => 'addons\webman\controller\ChannelBankController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelBankController/form',
        'title' => '编辑银行',
    ],
    //反水管理
    [
        'id' => 'addons\webman\controller\ChannelPlatformReverseWaterController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '反水管理',
        'children' => []
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlatformReverseWaterController\index',
        'pid' => 'addons\webman\controller\ChannelPlatformReverseWaterController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlatformReverseWaterController/index',
        'title' => '反水活动',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlatformReverseWaterController\form-post',
        'pid' => 'addons\webman\controller\ChannelPlatformReverseWaterController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelBankController/form',
        'title' => '添加配置',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlatformReverseWaterController\form-put',
        'pid' => 'addons\webman\controller\ChannelPlatformReverseWaterController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelBankController/form',
        'title' => '修改配置',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlatformReverseWaterController\waterDetail',
        'pid' => 'addons\webman\controller\ChannelPlatformReverseWaterController-',
        'action' => 'waterDetail',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelBankController/waterDetail',
        'title' => '反水奖励记录',
    ],
    [
        'id' => 'addons\webman\controller\ChannelPlatformReverseWaterController\profitSettlement',
        'pid' => 'addons\webman\controller\ChannelPlatformReverseWaterController\index',
        'action' => 'profitSettlement',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelPlatformReverseWaterController/profitSettlement',
        'title' => '批量结算',
    ],

    // ========== 渠道端充值满赠管理 ==========
    // 主菜单
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusActivityController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '充值满赠管理',
        'children' => []
    ],

    // 活动管理
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusActivityController\index',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusActivityController/index',
        'title' => '活动管理',
    ],
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusActivityController\form-get',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController\index',
        'action' => 'form',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusActivityController/form',
        'title' => '获取活动表单',
    ],
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusActivityController\form-post',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusActivityController/form',
        'title' => '添加活动',
    ],
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusActivityController\form-put',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusActivityController/form',
        'title' => '编辑活动',
    ],
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusActivityController\detail',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController\index',
        'action' => 'detail',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusActivityController/detail',
        'title' => '活动详情',
    ],

    // 订单管理
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusOrderController\index',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusOrderController/index',
        'title' => '订单管理',
    ],
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusOrderController\detail',
        'pid' => 'addons\webman\controller\ChannelDepositBonusOrderController\index',
        'action' => 'detail',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusOrderController/detail',
        'title' => '订单详情',
    ],

    // 统计报表
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusStatisticsController\index',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusStatisticsController/index',
        'title' => '统计报表',
    ],

    // 押码明细
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusBetDetailController\index',
        'pid' => 'addons\webman\controller\ChannelDepositBonusActivityController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusBetDetailController/index',
        'title' => '押码明细',
    ],
    [
        'id' => 'addons\webman\controller\ChannelDepositBonusBetDetailController\detail',
        'pid' => 'addons\webman\controller\ChannelDepositBonusBetDetailController\index',
        'action' => 'detail',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelDepositBonusBetDetailController/detail',
        'title' => '明细详情',
    ],

    // 限红管理
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController-',
        'pid' => 0,
        'url' => '',
        'group' => 'channel',
        'title' => '限红管理',
        'children' => []
    ],
    // 店家限红分配
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index',
        'pid' => 'addons\webman\controller\ChannelAdminUserLimitGroupController-',
        'action' => 'index',
        'method' => 'get',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminUserLimitGroupController/index',
        'title' => '店家限红分配',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index-delete',
        'pid' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index',
        'action' => 'index',
        'method' => 'delete',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminUserLimitGroupController/index',
        'title' => '删除限红分配',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\form-post',
        'pid' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index',
        'action' => 'form',
        'method' => 'post',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminUserLimitGroupController/form',
        'title' => '添加限红分配',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\form-put',
        'pid' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index',
        'action' => 'form',
        'method' => 'put',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminUserLimitGroupController/form',
        'title' => '修改限红分配',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\getStoreAdminOptions',
        'pid' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index',
        'action' => 'getStoreAdminOptions',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminUserLimitGroupController/getStoreAdminOptions',
        'title' => '获取店家选项',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\getLimitGroupOptions',
        'pid' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index',
        'action' => 'getLimitGroupOptions',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminUserLimitGroupController/getLimitGroupOptions',
        'title' => '获取限红组选项',
    ],
    [
        'id' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\getGamePlatformOptions',
        'pid' => 'addons\webman\controller\ChannelAdminUserLimitGroupController\index',
        'action' => 'getGamePlatformOptions',
        'method' => '',
        'group' => 'channel',
        'url' => 'ex-admin/addons-webman-controller-ChannelAdminUserLimitGroupController/getGamePlatformOptions',
        'title' => '获取游戏平台选项',
    ],
];
