name: Admin

# 1. 触发条件：只有 push 到 super9-master 分支时触发自动部署
on:
  push:
    branches:
      - super9-master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Baota WebHook
        # 2. 这里的 URL 替换成你从宝塔 WebHook 插件里复制出来的那个完整链接
        run: |
          curl -k -X GET "https://34.80.234.173:35812/hook?access_key=0AqlYDvVsBIWaB971XWzKN8VKOxQqmz5KVJYH18RI2i9KgK1&param=aaa"
